### ISSUE TITLE
Contribute to build the website

### ISSUE THREAD

**Issue by NoahDragon** [ayojs/ayojs.tech#2]
Hi all,

I would like to contribute to building the website for ayojs. I'm the current maintainer for [hexojs](https://hexo.io/), which a nodejs based static website generator (could easily migrate to ayojs). I believe using hexo can accelerate the building process.

If hexo is not an option, I still willing to join to contribute the website.

**Comment by ghost** [comment]
hi! we're currently not even sure how to build the website. discussion is ongoing over in our discord channel (see https://github.com/ayojs/ayo/issues/12#issuecomment-324444436), so if you want to join in, that'd be the best place to start right now! thank you!
